#!/bin/bash
echo Starting to build PhSim...
echo Attempting to start webpack...
npx webpack --config ./webpack.config.js
npx webpack --config ./webpack.min.config.js
echo PhSim build attempt completed. 