// Generated by TypeDefGen module 
// Built on Fri Oct 23 2020 23:01:06 GMT-0500 (Central Daylight Time)
PhSim.boolKey = ["Velocity","Force","Position","Translate","DeleteSelf","Draggable","Coin","Hazard","Health","Elevator","TransformCameraByObject","TransformWithCamera","KeyboardControls","Alert","Connection","SetAngle","Rotation","NoRotation","RectText","NumVar","SetNumVar","SetColor","SetBorderColor","SetLineWidth","PlayAudio","ObjLink_a","Game","DeleteSelf","ToggleLock","CircularConstraint","DeleteSelf","ToggleSemiLock"];
PhSim.boolKey_lc = ["velocity","force","position","translate","deleteSelf","draggable","coin","hazard","health","elevator","transformCameraByObject","transformWithCamera","keyboardControls","alert","connection","setAngle","rotation","noRotation","rectText","numVar","setNumVar","setColor","setBorderColor","setLineWidth","playAudio","objLink_a","game","deleteSelf","toggleLock","circularConstraint","deleteSelf","toggleSemiLock"];

 
 
/**
* @typedef {simpleEventOptions|Velocity}
* @property {Boolean} velocity - Boolean for enabling the velocity widget
* @property {Vector} vector - Velocity vector
*/
 
/**
* @typedef {simpleEventOptions|Force}
* @property {Boolean} force - Boolean for enabling the force widget
* @property {Vector} vector - Force vector
*/
 
/**
* @typedef {simpleEventOptions|Position}
* @property {Boolean} position - Boolean for enabling the position widget
* @property {Vector} vector - Position vector
*/
 
/**
* @typedef {simpleEventOptions|Translate}
* @property {Boolean} translate - Boolean for enabling the translation widget
* @property {Vector} vector - Translation vector
*/
 
/**
* @typedef {simpleEventOptions|DeleteSelf}
* @property {Boolean} deleteSelf - Boolean for enabling the force widget
*/
 
/**
* @typedef {Object|Draggable}
* @property {Boolean} deleteSelf - Boolean for enabling the force widget
*/
 
/**
* @typedef {Object|Coin}
* @property {Boolean} deleteSelf - Boolean for enabling the coin widget
*/
 
/**
* @typedef {Object|Hazard}
* @property {Boolean} deleteSelf - Boolean for enabling the hazard widget
*/
 
/**
* @typedef {Object|Health}
* @property {Boolean} deleteSelf - Boolean for enabling the health widget
*/
 
/**
* @typedef {Object|Elevator}
* @property {Boolean} elevator - Boolean for enabling the elevator widget
* @property {Vector} pointA - First point
* @property {Vector} pointB - Second point
*/
 
/**
* @typedef {Object|TransformCameraByObject}
* @property {Boolean} deleteSelf - Boolean for enabling the hazard widget
*/
 
/**
* @typedef {Object|TransformWithCamera}
* @property {Boolean} transformWithCamera - Boolean for determining the object moves with the camera
*/
 
/**
* @typedef {Object|KeyboardControls}
* @property {Number} up - Up velocity
* @property {Number} down - Down velocity
* @property {Number} left - Left velocity
* @property {Number} right - Right velocity
* @property {Boolean} keyboardControls - Boolean for enabling keyboard controls widget
*/
 
/**
* @typedef {Object|Alert}
* @property {String} buttonTxt - Button Text
* @property {String} name - Alert Name
* @property {String} text - Text Message
* @property {Boolean} alert - Boolean for enabling alert
*/
 
/**
* @typedef {Object|Connection}
* @property {LOAddress} objectA - First Object
* @property {LOAddress} objectB - Second Object
* @property {Boolean} connection - Right velocity
*/
 
/**
* @typedef {simpleEventOptions|SetAngle}
* @property {Number} cycle - Angle
* @property {Boolean} circularConstraintRotation - Down velocity
* @property {Boolean} rotation - Right velocity
*/
 
/**
* @typedef {simpleEventOptions|Rotation}
* @property {Number} cycle - Angle
* @property {Boolean} circularConstraintRotation - Down velocity
* @property {Boolean} rotation - Right velocity
*/
 
/**
* @typedef {Object|NoRotation}
* @property {Boolean} deleteSelf - Boolean for enabling the no rotation widget
*/
 
/**
* @typedef {Object|RectText}
* @property {String} content - Rectangular Text Content
* @property {String} font - Rectangular Text Font
* @property {Number} margin - Text Margin
* @property {Number} size - Text Margin
* @property {Number} bordersize - Text Margin
* @property {String} fill - Text Fill
* @property {Boolean} rectText - Content
* @property {String} lineWidth - Text Line Width
*/
 
/**
* @typedef {Object|NumVar}
* @property {String} name - undefined
* @property {Number} value - undefined
* @property {Boolean} numVar - undefined
*/
 
/**
* @typedef {simpleEventObjects|SetNumVar}
* @property {String} name - undefined
* @property {Number} value - undefined
* @property {Boolean} SetNumVar - undefined
*/
 
/**
* @typedef {simpleEventObjects|SetColor}
* @property {String} color - undefined
* @property {Boolean} setColor - undefined
*/
 
/**
* @typedef {simpleEventObjects|SetBorderColor}
* @property {String} color - undefined
* @property {Boolean} setBorderColor - undefined
*/
 
/**
* @typedef {simpleEventObjects|SetLineWidth}
* @property {Number} lineWidth - undefined
* @property {Boolean} setLineWidth - undefined
*/
 
/**
* @typedef {simpleEventObjects|PlayAudio}
* @property {String} src - undefined
* @property {Boolean} playAudio - undefined
*/
 
/**
* @typedef {simpleEventObjects|ObjLink_a}
* @property {LOAddress} target - undefined
* @property {Boolean} objLink_a - undefined
*/
 
/**
* @typedef {Object|Game}
* @property {Number} life - undefined
* @property {Number} goal - undefined
* @property {Number} score - undefined
* @property {Boolean} game - undefined
*/
 
/**
* @typedef {Object|DeleteSelf}
* @property {Boolean} deleteSelf - Boolean for enabling the coin widget
*/
 
/**
* @typedef {Object|ToggleLock}
* @property {Boolean} toggleLock - Boolean for enabling the coin widget
*/
 
/**
* @typedef {Object|CircularConstraint}
* @property {Boolean} circularConstraint - Boolean for enabling the circular constraint widget
* @property {Number} x - Boolean for enabling the circular constraint widget
* @property {Number} y - Boolean for enabling the circular constraint widget
*/
 
/**
* @typedef {Object|DeleteSelf}
* @property {Boolean} deleteSelf - Boolean for enabling the self-deletion widget
*/
 
/**
* @typedef {simpleEventOptions|ToggleSemiLock}
* @property {Boolean} toggleSemiLock - Boolean for enabling the toggle semi-lock widget
*/
 
/** 
 * @typedef {Velocity|Force|Position|Translate|DeleteSelf|Draggable|Coin|Hazard|Health|Elevator|TransformCameraByObject|TransformWithCamera|KeyboardControls|Alert|Connection|SetAngle|Rotation|NoRotation|RectText|NumVar|SetNumVar|SetColor|SetBorderColor|SetLineWidth|PlayAudio|ObjLink_a|Game|DeleteSelf|ToggleLock|CircularConstraint|DeleteSelf|ToggleSemiLock} Widget 
*/
